[package]
name = "arbiter_template"
version = "0.1.0"
edition = "2021"

[dependencies]
arbiter-core = { git = "https://github.com/primitivefinance/arbiter.git", branch = "arbiter/version" }
tokio = { version = "1.32.0", features = ["full"] }
ethers = { version = "2.0.10" }
serde_json = { version = "1.0.107" }
