[package]
name = "arbiter_template"
version = "0.1.0"
edition = "2021"

[dependencies]
arbiter-core = { version = "0.5.0" }
tokio = { version = "1.11.0", features = ["full"] }
ethers = { version = "2.0.10" }
