[package]
name = "example_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
arbiter-core = { git = "https://github.com/primitivefinance/arbiter", branch = "colin/collector-executor" }
artemis-core = { git = "https://github.com/paradigmxyz/artemis" }
tokio = { version = "1.11.0", features = ["full"] }
ethers = { git = "https://github.com/primitivefinance/ethers-rs" }
async-trait = "0.1.72"
anyhow = "1.0.44"
crossbeam-channel = "0.5.8"
