simulation = "Counter"
output_directory = "analysis/counter"

[trajectory]
# The type of price process to use.
process = "gbm"
# The number of steps in the process.
num_steps = 36500
# Starting seed for the price processes
seed = 10
# The number of distinct paths to use
num_paths = 10
# The initial price of the asset.
[trajectory.initial_price]
fixed = 1.0
# The start time of the process.
[trajectory.t_0]
fixed = 0.0
# The end time of the process.
[trajectory.t_n]
fixed = 10.0

[gbm]
# The drift of the process.
[gbm.drift]
fixed = 0.0
# start = -1.0
# end = 1.0
# steps = 11
# The volatility of the process.
[gbm.volatility]
# start = 0.1
# end = 1.0
# steps = 10
fixed = 0.5

[block]
timestep_size = 15
