name: foundry

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with binary
        uses: actions/checkout@v2
        with:
          repository: 'primitivefinance/arbiter'
          path: './arbiter'
          
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Build binary
        run: |
          cd arbiter
          cargo install --path .
          cd ..
          
      - name: List Files
        run: ls -la
        working-directory: .
          
      - name: Generate Bindings
        run: arbiter bind
        working-directory: .
      
      - name: Build project
        run: cargo build
        working-directory: .

